### ISSUE TITLE
Support for grouped Queries and Mutation

### ISSUE THREAD

**Issue by huzaifaali14** [anvilco/spectaql#101]
Is there a way to generate grouped queries and mutations just like [Dociql](https://github.com/wayfair/dociql/blob/master/config.yml). I have gone through the docs and YAML options and I couldn't find anything relevant. I guess `Dociql` is managing it through `usecase` option in YAML file.

<img width="560" alt="Screenshot 2021-09-02 at 3 49 24 PM" src="https://user-images.githubusercontent.com/30002668/131831511-914a27e1-a071-4544-816c-7d6c35ccf968.png">

Some thing like below would be great if we can achieve this. 

<img width="615" alt="Screenshot 2021-09-02 at 3 54 25 PM" src="https://user-images.githubusercontent.com/30002668/131831680-455280da-3215-4817-bb47-d08baad16626.png">
<img width="343" alt="Screenshot 2021-09-02 at 3 54 34 PM" src="https://user-images.githubusercontent.com/30002668/131831694-51e0dc0a-ea0d-4740-a608-a9a4417f2101.png">

**Comment by huzaifaali14** [comment]
Hi @newhouse any update on this one.

**Comment by newhouse** [comment]
Hi @huzaifaali14 and thanks for using SpectaQL!

There is not currently a way to do this in SpectaQL, unfortunately, but I do think this seems like something that it should support.

I'm trying to think about what might be the best way to expose this capability to users. My first thoughts are:
1. Allow for an additional `metadata` flag that can be used to optionally specify a `groupName`...then all Queries with the same `groupName` will be grouped together, and all Mutations with the same `groupName` will be grouped together.
2. This fits with the existing pattern of using `metadata` to get things like examples into your output.
3. Perhaps it could support a "dynamic grouping processor" (similar to the dynamic examples processor) capability that lets you write code that returns what group each thing should be in...though I'm hesitant to do that from the start since I don't see the value vs figuring out how to get it into the metadata from the various options for doing so that SpectaQL already supports.

Any thoughts?

**Comment by ab-tools** [comment]
A way of grouping would be great, but please also incorporate types in this regard (not only queries/mutations).

**Comment by itizarsa** [comment]
@newhouse I think exploring how Dociql achieve this might give us some idea.

**Comment by newhouse** [comment]
You can now customize your data arrangement via "themes" in SpectaQL `1.0`. [This issue response](https://github.com/anvilco/spectaql/issues/208) shows a good starting point for how you can accomplish it.
