### ISSUE TITLE
Feature-Request: Scoped Views instead of grouping

### ISSUE THREAD

**Issue by knotenpunkt** [anvilco/spectaql#195]
Scoped View:

Instead of grouping elements in the sidebar to something logical, we could have a by me so called scoped-view.

the User, who reads the document can select - for example via a dropdown list - a certain scoped view.  And then only the parts, which belong to that view are shown. The sidebar shrinks then to that parts and also the whole page. The other elements are just hidden.

There could be also some automatic-algorithm to decide which scoped views should exists.
Maybe we can have there a scoped-view for each operation. And All types/Scalars and so on which are used in that operation belongs then to that scoped view too. 

Also the document-creator-user himself can configure his own scoped-views also with different maybe logical belonging together operations and its types and so to one scoped view.

WhereI can select that scoped view? Maybe we can have there a Top-Navigation-Bar where this dropdown-selector lives, which includes also a scoped-all-view^^

For the automatic-scoped views we can have there some buttons/links in the operation-description itself to get fast a scoped view for that operation.

And moment^^ Yes i had now one more thought about this. We could also have such buttons in the types and so on.

So if i click in the type USER to that scoped-view button. Then all other types and operations are shown which are related to USER.

I think this and the modal-feature would be a really nice feature and a game changer to get a readable graphql documentation.

It is still a single-page-application. The elements are shown or hidden based on current scoped-view

What do you think about that, @newhouse ?

**Comment by knotenpunkt** [comment]
@newhouse i saw that this one isn't marked yet.
don't you think this is a good feature?

**Comment by newhouse** [comment]
It's not that I don't think this is a good feature, but:
- I am super busy with a huge re-write: https://github.com/anvilco/spectaql/pull/232
- This re-write will include the ability to do something kind of like this. See the "Dynamic Data Arrangement" capability
- Since it is not immediately obvious to me how valuable this is compared so other work I might do on this project, I would probably wait to see if other users find this issue and 👍  it etc.

What do you think about the "Dynamic Data Arrangment" capability? It will allow you to create arbitrary groupings in the Navigation and main content areas.
@knotenpunkt

**Comment by newhouse** [comment]
[This issue](https://github.com/anvilco/spectaql/issues/208
) highlights how a lot of what you're asking for can be implemented by anyone who would like this behavior.

Since it's not immediately clear to me that this should be a default, I am going to close this for now.
