### ISSUE TITLE
Why dependencies are not updated?

### ISSUE THREAD

**Issue by itizarsa** [anvilco/spectaql#210]
When I run the npm run audit, spectaql has a few vulnerable dependencies. 

I can also see bots have created PR for bumping dependencies. 

Is there any reason not to upgrade the dependencies?

**Comment by newhouse** [comment]
I recently went through and updated as many of the dependencies that I could that were "easy".

However, not everything is up to date because:

1. Some of the remaining dependencies are "major" updates with breaking changes that are non-trivial to adjust
2. I am in the process of re-writing a lot of SpectaQL, and will then be able to hopefully remove some of the offending dependencies
3. Dependabot PRs are not aware of breaking changes, and at best rely on tests to decide if the update is OK
4. While someone may be using SpectaQL differently, its main use case is to create documentation from inputs that _you_ own and control. So if there is going to be an exploit of a vulnerability, it is going to have to be _you_ exploiting that vuln against _yourself_.

**Comment by itizarsa** [comment]
@newhouse Thanks for the reply. As a user of your work, I would like to contribute to this library. 

I am happy to take up small work to understand how the library works and then would be able to contribute to big things. Also, it would be better if you could tell me where to look to understand how the library works internally.

Should I fix any breaking changes introduced while updating old dependencies?

**Comment by louisa-ba** [comment]
A lot of the warnings seem to come from grunt maybe look at using an alternative build tool like webpack?

**Comment by newhouse** [comment]
Closing for now thanks to 1.0. May need to move away from grunt at some point, yes.
