### ISSUE TITLE
Show all properties instead of fragments

### ISSUE THREAD

**Issue by amaleszewski** [anvilco/spectaql#219]
Hello! Thanks for your library, it's really great! But I have one question with which I'm struggling. I don't want to show in my examples a `...Fragment` properties, but every property from the model. Is that possible to achieve?

![image](https://user-images.githubusercontent.com/22931942/156752515-b76aa0ac-2482-48af-864c-2be8b3b574a6.png)

Look at this example, instead of `...OrderResponseFragment` I would like to have all properties from this response.

Thanks!

**Comment by Qsto33** [comment]
I must really say I agree here. My life without this feature is really dull. I tried to move on but I cant...

**Comment by newhouse** [comment]
Yes, I like this, too, as an _option_, but perhaps not the default.

The tricky part is that depending on your schema - specifically the number of fields on the return type - the output when expanding recursively deep can be very long...too long...and that's why by default it will only expand the top-level depth. I think it works well for people as the default.

However:
1) I'll noodle on ways to override the depth option either overall, or for specific queries/mutations/examples...but I'm not sure the latter will feel very good, and the former will probably make some situations better, but some worse.
2) This example looks like a "pagination" scenario, which I think _does_ make a bit more sense to expand deeper in that case. At least the 'items' field could/should be expanded, IMO. Perhaps I can add a way/option to
    1) Tell SpectaQL what your "pagination" scheme looks like.
    2) Expand the "Items" (or other pagination fields) when a pagination type is detected.

**Comment by amaleszewski** [comment]
Thanks for your response. I think option for configure it globally will be the best, and then for example you can add a "+" button at the left side of properties which could be expanded, like **items** or **pageInfo** in my case. Then it could be dynamically expanded by user on click (collapsed or uncollapsed by default, also configurable).

About the recursively deep expanding, then you can for example expand only 2 levels of it, and then in 3rd level just paste what's now here - a fragment of model with spread operator. It will be obvious then, that's it a recursion in property.

Please take a look on this: https://rejestr.io/api/info/v1/dokumentacja#operation/searchKrsOrgs - it's documentation based on [Redocly](https://github.com/Redocly/redoc). On the right side you can see that properties are expandable by user interaction and you have also option to collapse/expand all.

![image](https://user-images.githubusercontent.com/22931942/157009234-2eca582e-5fcc-4e1f-b234-1d0fa039fb00.png)

One more thing - it will be cool, when there will be possibility to see all return properties in model at the query level. So you don't need to click on model name, scroll down and then return, but on query level you see all return properties with their proper description. Like it's also in Redocly:

![image](https://user-images.githubusercontent.com/22931942/157009716-458ecfe1-61dc-4aa9-acf6-5b6d0db35095.png)

Regards
Adrian

**Comment by newhouse** [comment]
Support for a `fieldExpansionDepth` option now exists and is out in `1.1.0`.

Closing.
