### ISSUE TITLE
use NodeJS v14 as min-spec and sunset NodeJS v12 support per EOL (4/30/2022)

### ISSUE THREAD

**Issue by haysclark** [anvilco/spectaql#490]
**Security Support** for `NodeJS v12` officially ended on Apr 30, 2022 
@see https://endoflife.date/nodejs

Ending support for versions of _NodeJS_ that are no longer supported will reduce maintenance surface area.

If needed, a major or minor version bump of `specaql` may help communicate this change to the community.

**Comment by newhouse** [comment]
I'm going to have to think about whether the fact that Node 12 has been sunset means that this project should no longer worry about supporting Node 12 runtimes. Just because the Node project will not be updating 12 does not mean that there are not a lot of 12.x runtimes out there using SpectaQL.

I think it would be a good time to:
1. Decide when to stop supporting Node 12
2. Announce that time
3. Create a new Major version (`2.x.x`) that drops support for Node 12 and moves onwards

I'll think about it some more, but not sure this is something that we want to drop support for right away.

**Comment by newhouse** [comment]
This will be addressed in https://github.com/anvilco/spectaql/pull/524

**Comment by newhouse** [comment]
Done in `v2`!
