### ISSUE TITLE
Directive-driven documentation and metadata?

### ISSUE THREAD

**Issue by trevorr** [anvilco/spectaql#51]
Hello! I just tried spectaql for the first time, and it successfully generated nice-looking (but bare bones) documentation for my rather large API (5288 lines of SDL)!

My GraphQL service is entirely [SDL-first](https://github.com/trevorr/sdlfirst), with C/U/D mutations, SQL schema, and most Typescript resolver code generated based on directive-annotated SDL, so it contains many directives that declare semantics, validation, etc. Therefore, I'm wondering whether you have considered or have recommendations on how one might supply metadata (such as `undocumented`) or generate documentation snippets (e.g. "This field is read-only and has a maximum length of 40 characters.") using directives.

Obviously, there are very few standard directives (such as `@deprecated`), so most will be project/framework-specific. Therefore, custom code would likely be required to map a given set of directives onto the metadata supported by the documentation formatter. I think the question basically comes down to whether there is or could be a single place to hook up this user-supplied mapping function.

Another possibility would be to have a separate tool generate JSON metadata for spectaql based on SDL directives. That would work for the existing metadata features of examples and documented/undocumented. To support generated descriptions, I think additional metadata would be needed, such as `descriptionPrefix` and/or `descriptionSuffix`. Alternatively, the tool could also generate a new SDL file with generated descriptions inserted. This separate tool approach involves fewer or even no changes to spectaql, but likely involves more work to develop and use.

Anyway, just wondering if this is on your radar. If it sounds interesting and you can suggest how/where to support it, I'm happy to create a PR.

For sake of argument, here's an example type declaration with directives:

```graphql
type ContactAddress {
  id: ID! @rid # random base-62 ID
  principal: Principal! @immutable
  organization: Organization @immutable
  type: AddressType! @immutable
  address: String! @length(max: 255)
  label: String @length(max: 40)
  visibility: Visibility!
  systemUse: Boolean! @default(value: "false")
  createDate: DateTime! @sqlType(type: "timestamp") @createdAt
  lastVerified: DateTime @sqlType(type: "timestamp") @readonly
  _id: Int! @id @autoinc @undocumented
}
```

**Comment by newhouse** [comment]
Hmm, this is an interesting question.

To be quite honest, the level of support I'd be willing to put behind this (for now) will be proportional to the amount of capability that the GraphQL tools currently provides for it.

For example, in the way that I'm currently leveraging the `graphql` library, directive applications on, say, a `FIELD_DEFINITION` do not make their way into the Introspection Query results. This appears to be intentional: https://github.com/graphql/graphql-spec/issues/300 and https://stackoverflow.com/questions/65064766/is-there-any-way-to-read-graphql-directives-on-a-type-with-query-introspection

Of course, since you are the proud owner of the Schema SDL, perhaps there are other methods of getting at the applied directives via the GraphQL tools/utilities that SpectaQL can then leverage in some way to provide for doing cool things with the documentation...but a quick look into things did not lead me to any sort of "Eureka" moment. I encourage you to explore and tinker with these utils, and a decent starting point to trace back from can be found here: https://github.com/anvilco/spectaql/blob/main/app/spectaql/graphql-loaders.js#L8

Another option worth exploring might be seeing if you can have your server do the lifting as part of its Introspection Query response, where you add any SpectaQL-related "metadata" to the response, and/or manipulate the `description` for each field on its way out the door as necessary. Of course, then you need a GraphQL server involved in your process as opposed to just an SDL file.

I'm not sure what your GraphQL implementation is, or how easy this might be in Apollo (what we use at Anvil), but as food for thought, you can have a look at this Apollo plugin that I wrote that will add metadata to Introspection Query results for any purpose...but we use it for SpectaQL:
https://github.com/anvilco/apollo-server-plugin-introspection-metadata

Hope this helps, and let me know if you find anything interesting!

**Comment by gonzalezzfelipe** [comment]
Hey there, just wanting to leave my two cents here. I am working on a Python GraphQL API and want to use this to generate documentation, because there is no good framework for that on Python, at least that I have found. That means that I can't use the plugin to add metadata directly, I would have to translate it to Python. Also, we have disabled introspection for security reasons, so adding metadata to those queries is not an option either way. This means that I have no option but adding the metadata JSON file, that will have the `undocumented` directives there. This implies understanding the Apollo metadata API, whilst adding directives on the schema is a much more _graphql-esque_, dryer, and languange agnostic way to do it IMO. Maybe this use case helps in the adding the support for directives, maybe it doesn't, but at least I tried 🤷

**Comment by newhouse** [comment]
> This means that I have no option but adding the metadata JSON file, that will have the `undocumented` directives there. This implies understanding the Apollo metadata API

The metadata JSON file format is not (at least not intentionally or knowingly) specific to to Apollo - it's a completely made up structure by me, but appears to follow the generic/standard introspection query results structure...so I wouldn't call it or anything else (other than the plugin I wrote for Apollo) to be Apollo-specific.

I've jumped into this a little bit again just now, and here are my findings/thoughts:
- It does not seem like the Introspection Query results, nor the `GraphQLSchema` Javascript object that are created from an SDL with a custom directive like `@spectaql` defined and used in it will indicate the usage of that custom directive. In other words, simply defining a directive in SDL and using it like this:
```sdl
directive @spectaql(documented: Boolean) on OBJECT | FIELD_DEFINITION

type MyType @spectaql(documented: false) {
  ...
}
```
will not cause any indication in the outputs that SpectaQL has access to that the type `MyType` has been decorated with the `spectaql` directive.
- I could not find a way to make this happen easily/simply. I believe that custom directives' implementations and their side-effects are all you'd get.
- Perhaps a syntax could be considered for usage in the `description`, but I really dislike this idea/pattern, even though I've seen it used elsewhere.

Since this seems to only be an issue for Users who are going to provide `SDL`s to SpectaQL, perhaps I can try making some sort of an "extension" that:
- Can be turned on with some option
- Expects an SDL to be provided
- Will add some basic implementation for a `@spectaql` directive that will accept arguments and can make it come out as SpectaQL-friendly metadata that comes out in the Introspection Query Results that are used internally by SpectaQL even when an SDL is passed as the source.

This may work...

**Comment by newhouse** [comment]
OK @trevorr @gonzalezzfelipe @stephen-opal @rajington

I have added support for adding metadata in via a `@spectaql` directive. The usage is pretty straightforward, and reasonably customizable. It is now out in `main` and in version `1.5.0`.

I decided to make the options you pass a more generic `LIST` of objects that have the following shape: `{ key: String!, value: String! }`. This will allow for a bit more flexibility, IMO, even though it requires a bit more verbosity/verboseness to write.

Please see https://github.com/anvilco/spectaql#the-spectaql-directive for more information, and let me know how it works for you!

**Comment by newhouse** [comment]
@gonzalezzfelipe Is it working for you?

**Comment by gonzalezzfelipe** [comment]
> @gonzalezzfelipe Is it working for you?

Yep, it is working just fine 👍
