### ISSUE TITLE
CSS customization

### ISSUE THREAD

**Issue by iskdjim** [anvilco/spectaql#58]
hi guys,
as far as i unterstand it right, it should be possible to add some custom css to change the default css for the html.
unfortunately, i am not smart enough to get it working ;).

can maybe someone explain me, where i have to but the custom full.scss file.
have already added the cssBuildMode: full in my config.yml file.

thanks

**Comment by newhouse** [comment]
Hi @iskdjim and thanks for using SpectaQL!

Question - are you using SpectaQL via `npm`, or have you cloned the repo from Github?

**Comment by ShawnYcx** [comment]
I have the question about this. I'm using SpectaQL via npm and do not have app folder cloned. What kind of configurations do I need to setup scss override? Thanks

**Comment by newhouse** [comment]
> Figured out what my issue was

@ShawnYcx that's great that you figured out how to get things working for you! I'm actually interested in exactly how you've got things set up as I was not 100% following your scenario and solution.

Would you mind sharing a bit more?

**Comment by ShawnYcx** [comment]
> > Figured out what my issue was
> 
> @ShawnYcx that's great that you figured out how to get things working for you! I'm actually interested in exactly how you've got things set up as I was not 100% following your scenario and solution.
> 
> Would you mind sharing a bit more?

Sure. I like the default `cssBuildMode: full` stylings and I just wanted to override the sidebar styles, remove box shadow, etc...

### The problem
I was trying to override just the variable value in `/customizations/scss` but the issue was in `./app/stylesheet/_layout.scss` not all hex values are scss variable like it is in `./app/stylesheet/_basic.scss`.

### Reference to what I'm talking about _basic vs _layout
https://github.com/anvilco/spectaql/blob/cec26d487c5ed28fc2de00aa0230ef551d292788/app/stylesheets/_basic.scss#L52
https://github.com/anvilco/spectaql/blob/cec26d487c5ed28fc2de00aa0230ef551d292788/app/stylesheets/_layout.scss#L64

### The solution
The solution was simple. I just went through the `_layout.scss` file and replaced those static hex values with variables and is now overridable in my `/customization/scss`. This is useful for my use case because someone maintaining my code in the future might only want another color update and they won't have to change anything in the _layout file.

**Comment by newhouse** [comment]
> I'm using SpectaQL via npm and do not have app folder cloned

Thanks for posting @ShawnYcx ! This makes sense to me if you've cloned/forked the repo locally somewhere...but I thought you said you were using it via `npm`? Did you go into the `node_modules` folder of your project to make these edits then? I worry that those edits will be lost next time there's an update of the package...

**Comment by ShawnYcx** [comment]
Nope, I copied the `/app` folder into my source and used the `-a` cli command to change the default the app path.

https://github.com/anvilco/spectaql/blob/cec26d487c5ed28fc2de00aa0230ef551d292788/bin/spectaql.js#L38

**Comment by jared-fraser** [comment]
It would be great to get an example of how to generate with custom css via npm.

I have the following layout however the customizations are not being applied.

```
service/
  docs/
    api.yml
  customizations/
    scss/
      full.scss
  package.json
```

**Comment by JeromeErasmus** [comment]
Yeah can anyone give a working example of what the scss override folder structure should look like please?

not haveing any luck here either

**Comment by newhouse** [comment]
This is now supported in `0.15.0`, thanks to changes in [this PR](https://github.com/anvilco/spectaql/pull/237), via the [`additionalCssFile`](https://github.com/anvilco/spectaql/blob/main/config-example.yml#L14) YAML config option, or via the [`--additional-css-file`](https://github.com/anvilco/spectaql/blob/main/bin/spectaql.js#L59) CLI option.
