### ISSUE TITLE
Constructor arguments for c# records not documented

### ISSUE THREAD

**Issue by Adam-Kalman** [anvilco/spectaql#626]
Hi

Here is my case

![image](https://user-images.githubusercontent.com/59689961/207898500-636a9a17-252a-4965-bbc0-eace8854ad78.png)

and below is the result:

![image](https://user-images.githubusercontent.com/59689961/207898864-32d0fbb2-f512-4983-9994-0d3462ab021a.png)

while in class everything works fine.

Is there any workaround for this issue keeping the records and its arguments?

**Comment by newhouse** [comment]
Hello @Adam-Kalman  and thanks for writing in. This is most likely not an issue with SpectaQL but either your C# code for your GraphQL server, or the C# GraphQL server itself. I'm guessing that your C# code for your GraphQL server is resulting in a schema representation that you're not intending, but that would not be anything that SpectaQL can do anything about.

What I can do to help is to have a look at the input you are providing SpectaQL for your schema and confirm where the problem is from SpectaQL's point of view. Are you providing a live Introspection URL? An SDL file? An Introspection Query response JSON file?

Can you provide the raw input from whichever of those you're using here in this issue?

**Comment by Adam-Kalman** [comment]
Hello @newhouse,
Thank you for quick answer. 
You was right, the problem with records was not in SpectaQL itself but on my local environment. 
On production server constructor arguments in records are well documented, so sorry for the inconvenience.
Reinstall Visual Studio to the newest version solved this issue.

Regards.

**Comment by newhouse** [comment]
Glad to hear!
