### ISSUE TITLE
 Error thrown if you do not specify a Query

### ISSUE THREAD

**Issue by flmuel** [anvilco/spectaql#645]
Unfortunately, you must include a query to compile. If you don't:
```Error: Problem with Introspection Query Response```

The only workaround is (when you don't have metadata included) to insert a fake query in your schema and set introspection.queryDocumentedDefault to false.

Is this intentional? Right now I don't want any queries in my docs.

**Comment by newhouse** [comment]
@flmuel I'm not sure if I'd call this "intentional" as much as I'd call it "expected."

SpectaQL uses `graphql` under the hood, and when parsing input to build a schema that library appears to require there to be at least 1 Query.

I'm on the fence about whether to do something to support this case in SpectaQL when it seems like a schema without any Queries (or Mutations?) is not valid, and you can hide all Queries and Mutations from the output easily enough.

Why does your input schema not contain any Queries if SpectaQL is capable of filtering them all out from the resulting documentation?

**Comment by flmuel** [comment]
> Why does your input schema not contain any Queries if SpectaQL is capable of filtering them all out from the resulting documentation?

@newhouse 
What do you mean by that? My schema has queries :) 
Maybe I didn't write my starting point accurately. Currently I have GraphQL queries - but only mutations, none of type "query". I can't really believe that GQL needs a "query query" even though query mutations already exist in the schema. But if thats the case, its ok, I can live with that.

**Comment by newhouse** [comment]
I'm sure your _actual_ schema contains queries and/or mutations. I just meant that based on the limited information you've provided and the behavior you've described, I am assuming that the schema you're _passing_ to SpectaQL does not contain whatever it is that the `graphql` library expects/requires.

Sounds like you're able to accomplish what you want with the changes described. Will close for now.

**Comment by flmuel** [comment]
Apart from the small problem with the GraphQL spec, I am a fan of SpectaQL :)

Just for reference, current proposal regarding this topic: https://github.com/graphql/graphql-spec/issues/490
